import type { SysConfigParameters } from "@/domain/entities/sys-config";
import { type TurnDetails, type TurnFormProps, TurnTypeEnum } from "@/domain/entities/turns/turns";
import { StatusDefaultEnum } from "@/domain/usecases/status-default";

export function turnInitialFormValues(config: SysConfigParameters | null): TurnFormProps {
	const initValues: TurnDetails = {
		name: "",
		id: "",
		days: Array.from({ length: 7 }, (_, i) => ({
			id: "",
			total: "00:00",
			breakMinutes: 60,
			createdAt: "",
			dayIndex: i,
			isOff: false,
			startTime: "00:00",
			endTime: "",
			deletedAt: "",
			deletedBy: "",
			periodIndex: i,
			dayCutover: "00:00",
			week: "",
			updatedAt: "",
			workShiftId: "",
			periods: Array.from({ length: 2 }).map((_, i) => {
				return {
					id: "",
					breakMinutes: 60,
					startTime: "",
					endTime: "",
					workShiftDayId: "",
					periodIndex: i + 1,
					total: "",
				};
			}),
		})),
		periods: "2",
		patternType: TurnTypeEnum.weekly,
		status: StatusDefaultEnum.active,
		cycleLengthDays: "7",
		entriesAndOutDays: [],
		dsrTimingCode: "07:20",
		dsrHolidayDiscountingCode: "",
		dsrDiscountingCode: "",
		maximumDsrAbsences: "00:00",
		compensationModeCode: "",
		considerClt58Art: true,
		seeNR17FieldNameCode: "",
		deducingFromExtraTimeModeCode: "",
		actionUponSurpassingAbsenceLimitCode: "",
		actionUponSurpassingExtraTimeLimitCode: "",
		extendedNightlyShiftCode: "",
		extraTimeUnderAnHourCode: "",
		freeLunchCode: "",
		extraHourCalculationModeCode: "",
		interspersedOvertimePercentage: "",
		minimumIntervalValue: "11:00",
		nightlyShiftEndTimeCode: "05:00",
		nightlyFactorCode: "00:52:30",
		nightlyShiftStartTimeCode: "22:00",
		workingModeCode: "",
		periodToConsiderFreeLunch: "2",
		sundaysAndHolidaysOnTurnOfDayCode: "0",
		absenceToleranceInMinutes: "5",
		punchingToleranceInMinutes: "5",
		dailyMinimumAbsentInMinutes: "10",
		dailyMinimumExtraHoursInMinutes: "10",
		companyId: "",
		policyId: "",
	};
	if (!config) return initValues;
	const {
		punchingToleranceInMinutes,
		absenceToleranceInMinutes,
		dailyMinimumExtraHoursInMinutes,
		dailyMinimumAbsentInMinutes,
		dsrTime,
		compensationMode,
		deducingFromExtraTimeMode,
		extraHourCalculationMode,
		yesNo,
		extraTimeUnderAnHour,
		workingMode,
		actionUponSurpassingLimit,
		dsrHolidayDiscounting,
		extendedNightlyShift,
		dsrDiscounting,
	} = config;
	return {
		...initValues,
		punchingToleranceInMinutes,
		absenceToleranceInMinutes,
		dailyMinimumExtraHoursInMinutes,
		dailyMinimumAbsentInMinutes,
		dsrTimingCode: dsrTime,
		compensationModeCode: compensationMode[0].code.toString(),
		deducingFromExtraTimeModeCode: deducingFromExtraTimeMode[0].code.toString(),
		extraHourCalculationModeCode: extraHourCalculationMode[2].code.toString(),
		freeLunchCode: yesNo[1].code.toString(),
		extraTimeUnderAnHourCode: extraTimeUnderAnHour[1].code.toString(),
		workingModeCode: workingMode[0].code.toString(),
		interspersedOvertimePercentage: "50",
		seeNR17FieldNameCode: yesNo[1].code.toString(),
		actionUponSurpassingExtraTimeLimitCode: actionUponSurpassingLimit[0].code.toString(),
		actionUponSurpassingAbsenceLimitCode: actionUponSurpassingLimit[0].code.toString(),
		dsrHolidayDiscountingCode: dsrHolidayDiscounting[2].code.toString(),
		extendedNightlyShiftCode: extendedNightlyShift[2].code.toString(),
		dsrDiscountingCode: dsrDiscounting[1].code.toString(),
	};
}
