const {
	NEXT_PUBLIC_MAPS_KEY,
	NEXT_PUBLIC_MAPS_ID,
	NEXT_PUBLIC_MAPS_GEOCODE_API,
	NEXT_PUBLIC_API_BASE_URL,
	NEXT_PUBLIC_IMG_PROTOCOL,
	NEXT_PUBLIC_LOCALHOST,
	NEXT_PUBLIC_SYS_CONFIG_SECRET,
	NEXT_PUBLIC_IMG_PORT,
	NEXT_PUBLIC_IMG_PATH,
	NEXT_PUBLIC_IMG_FULL_URL,
	NEXT_PUBLIC_PUSHER_APP_ID,
	NEXT_PUBLIC_PUSHER_KEY,
	NEXT_PUBLIC_PUSHER_SECRET,
	NEXT_PUBLIC_PUSHER_CLUSTER,
	NEXT_PUBLIC_PUSHER_USE_TLS,
	NEXT_PUBLIC_API_WEB_SOCKET,
	NEXT_PUBLIC_WEB_SOCKET_PATH,
	NEXT_PUBLIC_API_LOCAL,
} = process.env;

const nextConfig = {
	async redirects() {
		return [
			{ source: "/registrations", destination: "/registrations/positions", permanent: true },
			{ source: "/hours", destination: "/hours/turns", permanent: true },
		];
	},

	images: {
		remotePatterns: [
			{
				// protocol: NEXT_PUBLIC_IMG_PROTOCOL || "http",
				protocol: NEXT_PUBLIC_IMG_PROTOCOL || "https",
				hostname: NEXT_PUBLIC_LOCALHOST || "img.app.dev.ponto.cloud",
				port: NEXT_PUBLIC_IMG_PORT || "3001",
				pathname: `${NEXT_PUBLIC_IMG_PATH || "/data/"}**`,
			},
		],
	},

	env: {
		SYS_CONFIG_SECRET: NEXT_PUBLIC_SYS_CONFIG_SECRET,
		MAPS_KEY: NEXT_PUBLIC_MAPS_KEY,
		MAPS_ID: NEXT_PUBLIC_MAPS_ID,
		MAPS_GEOCODE_API: NEXT_PUBLIC_MAPS_GEOCODE_API,
		API_BASE_URL: NEXT_PUBLIC_API_BASE_URL,
		IMG_URL: NEXT_PUBLIC_IMG_FULL_URL,
		PUSHER_APP_ID: NEXT_PUBLIC_PUSHER_APP_ID,
		PUSHER_KEY: NEXT_PUBLIC_PUSHER_KEY,
		PUSHER_SECRET: NEXT_PUBLIC_PUSHER_SECRET,
		PUSHER_CLUSTER: NEXT_PUBLIC_PUSHER_CLUSTER,
		PUSHER_USE_TLS: NEXT_PUBLIC_PUSHER_USE_TLS,
		API_WEBSOCKET: NEXT_PUBLIC_API_WEB_SOCKET,
		WEBSOCKET_PATH: NEXT_PUBLIC_WEB_SOCKET_PATH,
		API_LOCAL: NEXT_PUBLIC_API_LOCAL,
	},
};

export default nextConfig;
