import type { CompanyFormProps } from "@/domain/entities/companies";
import { StatusDefaultEnum } from "@/domain/usecases/status-default";

export const companyInitialFormValues: CompanyFormProps = {
  id: "",
  name: "",
  parentCompanyId: "",
  fantasyName: "",
  cnpj: "",
  caepf: "",
  ceicno: "",
  city: "",
  ie: "",
  isReseller: false,
  resellerId: "",
  nsr: "",
  planId: "",
  radius: "",
  responsibleCpf: "",
  responsibleEmail: "",
  responsibleName: "",
  responsibleSurname: "",
  sheetCode: "",
  trade: "",
  size: 0,
  startDay: "",
  street: "",
  number: "",
  state: "",
  neighborhood: "",
  zip: "",
  complement: "",
  timeZone: "",
  countryPhoneCode: "",
  collaboratorIds: [],
  centerCostIds: [],
  positionIds: [],
  delimitations: [],
  departmentIds: [],
  status: StatusDefaultEnum.active,
  color: "sky"
};
