import { type CollaboratorFormProps, CollaboratorMarkupEnum } from "@/domain/entities/collaborator/collaborator";
import { CollaboratorStatusEnum } from "@/domain/entities/collaborator/collaborator-status";

export const collaboratorInitialFormValues: CollaboratorFormProps = {
  extraTimes: [],
  workShiftAssignments: [],
  imageUrl: "",
  registerMark: true,
  name: "",
  surname: "",
  company: "",
  department: "",
  position: "",
  status: CollaboratorStatusEnum.active,
  email: "",
  pis: "",
  hasNoPis: false,
  cpf: "",
  dtAdmission: null,
  dtStartSystem: null,
  costCenter: "",
  positionTrust: "",
  registration: "",
  sheet: "",
  ctps: "",
  clt: "",
  rg: "",
  dtBirthday: new Date(),
  gender: "",
  nationality: "",
  placeOfBirth: "",
  civilState: "",
  socialName: "",
  cnh: "",
  categoryCnh: "",
  dtMaturityCnh: new Date(),
  zipcode: "",
  neighborhood: "",
  street: "",
  code: "",
  city: "",
  state: "",
  telephone: "",
  extension: "",
  cell: "",
  whatsApp: "",
  fathersName: "",
  fathersTelephone: "",
  mothersName: "",
  mothersTelephone: "",
  extraHours: [],
  hourBanks: [],
  perfil: "",
  username: "",
  password: "",
  alterPasswordFirstLogin: false,
  geo: [],
  markupDefault: CollaboratorMarkupEnum.WEB,
  fuso: "",
  web: {
    badge: false,
    barCode: false,
    biometricRecognition: false,
    facialRecognition: false,
    hasAccess: false,
    photo: false,
    pin: false,
    throwJustify: false,
    qrCode: false,
    pointMark: false,
  },
  mobile: {
    badge: false,
    barCode: false,
    biometricRecognition: false,
    facialRecognition: false,
    hasAccess: false,
    photo: false,
    pin: false,
    throwJustify: false,
    qrCode: false,
    pointMark: false,
  }
};
