export enum RequestManagementTypeEnum {
	REQUEST = "REQUEST",
	OFFLINE_MARK = "OFFLINE_MARK",
	GEO_DELIMITATION = "GEO_DELIMITATION",
	FAKE_GPS = "FAKE_GPS",
	NO_RECOGNIZE_PHOTO = "NO_RECOGNIZE_PHOTO",
}
